/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 94d58043-7081-4bfa-9410-75da27700493

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of the critical strip, critical line, and the Klein four orbit {s, 1-s, star(s), 1-star(s)}.
-/
def criticalStrip : Set ℂ := {s | 0 < s.re ∧ s.re < 1}

def criticalLine : Set ℂ := {s | s.re = 1/2}

def kleinFourOrbit (s : ℂ) : Set ℂ := {s, 1 - s, star s, 1 - star s}

/-
Definition of helix radius p^(-σ) and phase e^(-it log p). Theorem: The radii match (p^(-σ) = p^{-(1-σ)}) if and only if σ = 1/2.
-/
noncomputable def helixRadius (p : ℕ) (σ : ℝ) : ℝ := (p : ℝ) ^ (-σ)

noncomputable def helixPhase (p : ℕ) (t : ℝ) : ℂ := Complex.exp (-Complex.I * t * Real.log p)

theorem reflection_radius_match_iff_half (p : ℕ) (hp : p.Prime) (σ : ℝ) :
  helixRadius p σ = helixRadius p (1 - σ) ↔ σ = 1/2 := by
    simp [helixRadius];
    rw [ Real.rpow_def_of_pos, Real.rpow_def_of_pos ] <;> norm_num <;> ring;
    · constructor <;> intro h <;> nlinarith [ Real.log_pos ( Nat.one_lt_cast.mpr hp.one_lt ) ];
    · exact hp.pos;
    · exact hp.pos

/-
Definition of helix bend as |p^(-σ) - p^{-(1-σ)}|. Theorem: Bend is zero iff σ=1/2.
-/
noncomputable def helixBend (p : ℕ) (σ : ℝ) : ℝ := |helixRadius p σ - helixRadius p (1 - σ)|

theorem helixBend_eq_zero_iff_half (p : ℕ) (hp : p.Prime) (σ : ℝ) :
  helixBend p σ = 0 ↔ σ = 1/2 := by
    unfold helixBend;
    rw [ abs_eq ] <;> norm_num [ reflection_radius_match_iff_half p hp σ ];
    rw [ sub_eq_zero, reflection_radius_match_iff_half p hp ]

/-
Definitions of prime decoding and deprojected value. Theorem: Deprojected value is p iff σ=1/2.
-/
noncomputable def decodePrime (r : ℝ) : ℝ := r ^ (-2 : ℝ)

noncomputable def deprojectedValue (p : ℕ) (σ : ℝ) : ℝ := decodePrime (helixRadius p σ)

theorem deprojectedValue_eq_self_iff_half (p : ℕ) (hp : p.Prime) (σ : ℝ) :
  deprojectedValue p σ = p ↔ σ = 1/2 := by
    unfold deprojectedValue;
    unfold decodePrime helixRadius;
    rw [ ← Real.rpow_mul ] <;> ring <;> norm_num [ hp.ne_zero ];
    rw [ Real.rpow_def_of_pos ] <;> norm_num [ hp.pos ];
    rw [ ← Real.exp_log ( Nat.cast_pos.mpr hp.pos ) ] ; norm_num [ Real.exp_ne_zero ] ; constructor <;> intro <;> nlinarith [ Real.log_pos ( Nat.one_lt_cast.mpr hp.one_lt ) ] ;

/-
Theorem: Deprojected values match (p^(2σ) = p^(2(1-σ))) iff σ=1/2.
-/
theorem deprojectedValue_symmetry_iff_half (p : ℕ) (hp : p.Prime) (σ : ℝ) :
  deprojectedValue p σ = deprojectedValue p (1 - σ) ↔ σ = 1/2 := by
    unfold deprojectedValue;
    unfold decodePrime helixRadius;
    norm_num [ ← Real.rpow_mul ( Nat.cast_nonneg p ) ];
    norm_num [ Real.rpow_def_of_pos, hp.pos ];
    constructor <;> intro <;> nlinarith [ Real.log_pos ( Nat.one_lt_cast.mpr hp.one_lt ) ]

/-
Definition of reconstructed zeta function as ζ(2σw). Theorem: At σ=1/2, reconstructed zeta equals canonical zeta.
-/
noncomputable def reconstructedZeta (σ : ℝ) (w : ℂ) : ℂ := riemannZeta (2 * σ * w)

theorem reconstructedZeta_consistent_at_half (w : ℂ) :
  reconstructedZeta 0.5 w = riemannZeta w := by
    unfold reconstructedZeta riemannZeta;
    norm_num

/-
Definition of spectral energy using norm squared. Theorem: Spectral energy at σ ≠ 1/2 differs from canonical.
-/
noncomputable def spectralEnergy (σ : ℝ) (w : ℂ) : ℝ := Complex.normSq (reconstructedZeta σ w)

theorem spectralEnergy_disagreement_with_canonical (σ : ℝ) (hσ : σ ≠ 1/2) (h_range : 0 < σ ∧ σ < 1) :
  ∃ w, spectralEnergy σ w ≠ spectralEnergy 0.5 w := by
    unfold spectralEnergy;
    -- The zeta function has a pole of order 1 at $w = 1$, so $\lim_{w \to 1} \zeta(w) = \infty$.
    have h_zeta_pole : Filter.Tendsto (fun w : ℝ => Complex.normSq (riemannZeta w)) (nhdsWithin 1 (Set.Ioi 1)) Filter.atTop := by
      -- The Riemann zeta function has a pole of order 1 at $w = 1$, so $\lim_{w \to 1} \zeta(w) = \infty$. This follows from the fact that the harmonic series diverges.
      have h_harmonic : Filter.Tendsto (fun w : ℝ => ∑' n : ℕ, (1 : ℝ) / (n + 1 : ℝ) ^ w) (nhdsWithin 1 (Set.Ioi 1)) Filter.atTop := by
        refine' Filter.tendsto_atTop.mpr _;
        intro b
        obtain ⟨N, hN⟩ : ∃ N : ℕ, ∑ n ∈ Finset.range N, (1 : ℝ) / (n + 1 : ℝ) > b := by
          exact not_summable_iff_tendsto_nat_atTop_of_nonneg ( fun _ => by positivity ) |>.1 ( by exact_mod_cast mt ( summable_nat_add_iff 1 |>.1 ) Real.not_summable_one_div_natCast ) |> fun h => h.eventually_gt_atTop b |> fun h => h.exists;
        -- Since $\sum_{n=1}^{N} \frac{1}{n^s}$ is continuous at $s=1$, we can bring the limit inside.
        have h_cont : Filter.Tendsto (fun s : ℝ => ∑ n ∈ Finset.range N, (1 : ℝ) / (n + 1 : ℝ) ^ s) (nhdsWithin 1 (Set.Ioi 1)) (nhds (∑ n ∈ Finset.range N, (1 : ℝ) / (n + 1 : ℝ))) := by
          exact tendsto_nhdsWithin_of_tendsto_nhds ( ContinuousAt.tendsto ( by exact tendsto_finset_sum _ fun _ _ => ContinuousAt.div continuousAt_const ( ContinuousAt.rpow ( continuousAt_const.add continuousAt_const ) continuousAt_id <| Or.inl <| by linarith ) <| by positivity ) |> fun h => h.trans <| by norm_num );
        filter_upwards [ h_cont.eventually ( lt_mem_nhds hN ), self_mem_nhdsWithin ] with s hs₁ hs₂ using le_trans hs₁.le <| Summable.sum_le_tsum ( Finset.range N ) ( fun _ _ => by positivity ) <| by simpa using summable_nat_add_iff 1 |>.2 <| Real.summable_one_div_nat_rpow.2 hs₂.out;
      have h_zeta_eq_harmonic : ∀ w : ℝ, 1 < w → riemannZeta w = ∑' n : ℕ, (1 : ℝ) / (n + 1 : ℝ) ^ w := by
        intro w hw; norm_cast; simp +decide [ zeta_eq_tsum_one_div_nat_add_one_cpow, hw ] ;
        rw [ Complex.ofReal_tsum ] ; norm_num [ Complex.ofReal_cpow ( add_nonneg ( Nat.cast_nonneg _ ) zero_le_one ) ];
      refine' Filter.Tendsto.congr' _ ( by simpa [ Complex.normSq_eq_norm_sq ] using h_harmonic.atTop_mul_atTop₀ h_harmonic );
      filter_upwards [ self_mem_nhdsWithin ] with w hw ; aesop;
    contrapose! h_zeta_pole;
    -- Since $\zeta(2\sigma w)$ is continuous at $w = 1$, its norm squared is also continuous at $w = 1$.
    have h_cont : ContinuousAt (fun w : ℝ => Complex.normSq (riemannZeta (2 * σ * w))) 1 := by
      refine' ContinuousAt.comp ( Complex.continuous_normSq.continuousAt ) _;
      refine' ContinuousAt.comp ( show ContinuousAt ( fun w : ℂ => riemannZeta w ) ( 2 * σ * 1 ) from _ ) ( Continuous.continuousAt ( by continuity ) );
      refine' ( differentiableAt_riemannZeta _ ).continuousAt;
      norm_num [ Complex.ext_iff ] ; cases lt_or_gt_of_ne hσ <;> linarith;
    exact not_tendsto_atTop_of_tendsto_nhds ( h_cont.mono_left inf_le_left |> fun h => h.congr' <| Filter.eventuallyEq_of_mem self_mem_nhdsWithin fun x hx => by have := h_zeta_pole x; unfold reconstructedZeta at *; ring_nf at *; aesop )

/-
Definition of detectorPasses. Theorem: Detector passes iff σ=1/2 (within the strip).
-/
def detectorPasses (σ : ℝ) : Prop := ∀ w : ℂ, spectralEnergy σ w = spectralEnergy 0.5 w

theorem detectorPasses_iff_half (σ : ℝ) (h_range : 0 < σ ∧ σ < 1) :
  detectorPasses σ ↔ σ = 1/2 := by
    -- By definition of detectorPasses, we know that detectorPasses σ ↔ σ = 1 / 2.
    unfold detectorPasses; (
    constructor <;> intro hσ;
    · have := spectralEnergy_disagreement_with_canonical σ; aesop;
    · norm_num [ hσ ])

/-
Definition of FaithfulReconstruction. Theorem: Faithful reconstruction occurs iff σ=1/2.
-/
def FaithfulReconstruction (σ : ℝ) : Prop := ∀ p : ℕ, p.Prime → deprojectedValue p σ = p

theorem faithfulReconstruction_iff_half (σ : ℝ) :
  FaithfulReconstruction σ ↔ σ = 1/2 := by
  constructor
  · intro h
    have h2 := h 2 Nat.prime_two
    rw [deprojectedValue_eq_self_iff_half 2 Nat.prime_two] at h2
    exact h2
  · intro h p hp
    rw [deprojectedValue_eq_self_iff_half p hp]
    exact h

/-
Theorems: If σ ≠ 1/2, then FaithfulReconstruction fails (Check B) and detectorPasses fails (Check A).
-/
theorem check_B_fails (σ : ℝ) (hσ : σ ≠ 1/2) : ¬FaithfulReconstruction σ := by
  intro h
  rw [faithfulReconstruction_iff_half] at h
  contradiction

theorem check_A_fails (σ : ℝ) (hσ : σ ≠ 1/2) (h_range : 0 < σ ∧ σ < 1) : ¬detectorPasses σ := by
  intro h
  rw [detectorPasses_iff_half σ h_range] at h
  contradiction

/-
Bridge Theorem: If riemannZeta s = 0, then reconstructedZeta 0.5 s = 0. This anchors the zero to the canonical reconstruction.
-/
theorem bridge_zero_to_half_reconstruction (s : ℂ) (hs : riemannZeta s = 0) :
  reconstructedZeta 0.5 s = 0 := by
  rw [reconstructedZeta_consistent_at_half, hs]

/-
Theorem: If riemannZeta s = 0 and Re(s) > 1/√2, then reconstructedZeta(Re(s), s) ≠ 0. This shows a mismatch for zeros far from the critical line.
-/
theorem mismatch_at_large_sigma (s : ℂ) (h_zero : riemannZeta s = 0) (h_large : 1 / Real.sqrt 2 < s.re) :
  reconstructedZeta s.re s ≠ 0 := by
    -- By the properties of the Riemann zeta function, we know that $\zeta(s)$ is non-zero for $\Re(s) > 1$.
    have h_zeta_nonzero : ∀ s : ℂ, 1 < s.re → riemannZeta s ≠ 0 := by
      exact fun s a ↦ riemannZeta_ne_zero_of_one_lt_re a;
    convert h_zeta_nonzero ( 2 * s.re * s ) _ using 1;
    norm_num at *;
    rw [ inv_eq_one_div, div_lt_iff₀ ] at h_large <;> nlinarith [ Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two ]

/-
Theorem: If the helix bend is non-zero (at p=0? No, bend is defined for primes. Let's use a universal quantifier or a specific prime). If helixBend p σ ≠ 0 for some p, then riemannZeta s ≠ 0.
-/
theorem geometric_exclusion_of_zeros (s : ℂ) (h_bend : helixBend 0 s.re ≠ 0) :
  riemannZeta s ≠ 0 := by
    contrapose! h_bend;
    unfold helixBend;
    unfold helixRadius;
    by_cases h : s.re = 0 <;> by_cases h' : 1 - s.re = 0 <;> simp +decide [ h, h' ];
    · linarith;
    · have := @riemannZeta_ne_zero_of_one_le_re ( 1 - s ) ; simp_all +decide [ Complex.ext_iff ] ;
      have := @riemannZeta_one_sub s; simp_all +decide [ Complex.ext_iff ] ;
      by_cases hi : s.im = 0 <;> simp_all +decide;
      norm_num [ show s = 0 by simpa [ Complex.ext_iff ] using ⟨ h, hi ⟩ ] at *;
      norm_num [ riemannZeta ] at *;
      norm_num [ HurwitzZeta.hurwitzZetaEven ] at *;
    · -- Since $s.re = 1$, we have $s = 1 + it$ for some $t \in \mathbb{R}$.
      obtain ⟨t, ht⟩ : ∃ t : ℝ, s = 1 + t * Complex.I := by
        exact ⟨ s.im, by simpa [ Complex.ext_iff ] using by linarith ⟩;
      have := @riemannZeta_ne_zero_of_one_le_re ( 1 + t * Complex.I ) ; aesop;
    · rw [ Real.zero_rpow ( sub_ne_zero_of_ne <| by aesop ) ]

/-
Finding the lemma for division inequality.
-/
example (a b c : ℝ) (hc : 0 < c) : a / c < b ↔ a < b * c := by exact div_lt_iff₀ hc

/-
Checking full names of filter lemmas.
-/
#check nhdsWithin_le_nhds
#check tendsto_nhdsWithin_of_tendsto_nhds_of_eventually_within

/-
Checking filter lemma names.
-/
#check tendsto_nhdsWithin_of_tendsto_nhds
#check self_mem_nhdsWithin
#check nhdsWithin_le_nhds

/-
Helper lemma: The norm of the Riemann Zeta function tends to infinity as s approaches 1.
-/
theorem norm_riemannZeta_tendsto_atTop_one : Filter.Tendsto (fun s : ℂ => ‖riemannZeta s‖) (nhdsWithin 1 {1}ᶜ) Filter.atTop := by
  -- The Riemann zeta function has a simple pole at $s=1$ with residue $1$, so $|ζ(s)|$ tends to infinity as $s$ approaches $1$.
  have h_pole : Filter.Tendsto (fun s : ℂ => ‖riemannZeta s‖ * ‖s - 1‖) (nhdsWithin 1 {1}ᶜ) (nhds 1) := by
    have h_pole : Filter.Tendsto (fun s : ℂ => (s - 1) * riemannZeta s) (nhdsWithin 1 {1}ᶜ) (nhds 1) := by
      exact HurwitzZeta.hurwitzZetaEven_residue_one 0;
    simpa [ mul_comm ] using h_pole.norm;
  -- Since ‖s - 1‖ tends to 0 as s approaches 1, and the product ‖riemannZeta s‖ * ‖s - 1‖ tends to 1, it follows that ‖riemannZeta s‖ must tend to infinity.
  have h_tendsto_inf : Filter.Tendsto (fun s : ℂ => ‖riemannZeta s‖ * ‖s - 1‖ / ‖s - 1‖) (nhdsWithin 1 {1}ᶜ) Filter.atTop := by
    apply_rules [ Filter.Tendsto.pos_mul_atTop, h_pole ];
    · norm_num;
    · refine' Filter.Tendsto.inv_tendsto_nhdsGT_zero _;
      exact tendsto_norm_sub_self_nhdsNE 1;
  refine h_tendsto_inf.congr' ( by filter_upwards [ self_mem_nhdsWithin ] with s hs using by rw [ mul_div_cancel_right₀ _ ( norm_ne_zero_iff.mpr <| sub_ne_zero.mpr hs ) ] )

/-
Theorem: riemannZeta cannot be invariant under scaling w -> cw for c != 1. Proof uses the pole at s=1.
-/
theorem scaling_implies_contradiction (c : ℝ) (hc : 0 < c) (hc_ne : c ≠ 1) :
  ¬(∀ w : ℂ, riemannZeta (c * w) = riemannZeta w) := by
    by_contra h;
    -- Consider the limit of the zeta function as $s$ approaches $1$ from the right.
    have h_lim_right : Filter.Tendsto (fun s : ℂ => riemannZeta s) (nhdsWithin 1 {1}ᶜ) (nhds (riemannZeta 1)) := by
      have h_lim_right : ContinuousAt (fun s : ℂ => riemannZeta (c * s)) 1 := by
        refine' ContinuousAt.comp ( show ContinuousAt ( fun s => riemannZeta s ) _ from _ ) ( ContinuousAt.mul continuousAt_const continuousAt_id );
        refine' ( differentiableAt_riemannZeta _ ).continuousAt;
        aesop;
      simpa only [ h ] using h_lim_right.tendsto.mono_left inf_le_left;
    exact not_tendsto_atTop_of_tendsto_nhds ( h_lim_right.norm ) ( norm_riemannZeta_tendsto_atTop_one )

/-
Checking if scaling_implies_contradiction exists.
-/
#check scaling_implies_contradiction

/-
Lemma: A sequence of zeros converging to 0 implies zeta(0) = 0, which is false.
-/
theorem zero_limit_contradiction (f : ℕ → ℂ) (h_lim : Filter.Tendsto f Filter.atTop (nhds 0)) (h_zero : ∀ n, riemannZeta (f n) = 0) : False := by
  -- Since $f n$ tends to $0$, we have that $\zeta(f n)$ tends to $\zeta(0)$.
  have h_tendsto_zero : Filter.Tendsto (fun n => riemannZeta (f n)) Filter.atTop (nhds (riemannZeta 0)) := by
    have h_cont : ContinuousAt riemannZeta 0 := by
      refine' ( differentiableAt_riemannZeta _ ).continuousAt;
      norm_num;
    exact h_cont.tendsto.comp h_lim;
  -- Since $\zeta(0) = -1/2$, we have that $\zeta(f n)$ tends to $-1/2$, which contradicts the fact that $\zeta(f n) = 0$ for all $n$.
  have h_contradiction : riemannZeta 0 = 0 := by
    exact tendsto_nhds_unique h_tendsto_zero ( by simpa only [ h_zero ] using tendsto_const_nhds );
  exact absurd h_contradiction ( by erw [ riemannZeta_zero ] ; norm_num )

/-
Definition of s_seq and lemma for its real part recurrence.
-/
noncomputable def s_seq (s : ℂ) : ℕ → ℂ
| 0 => s
| n+1 => 2 * (s_seq s n).re * (s_seq s n)

theorem s_seq_re (s : ℂ) (n : ℕ) : (s_seq s (n + 1)).re = 2 * (s_seq s n).re ^ 2 := by
  simp [s_seq, Complex.mul_re]
  ring

/-
Closed form for the real part of s_seq: Re(s_n) = (1/2) * (2 * Re(s))^(2^n).
-/
theorem s_seq_re_closed_form (s : ℂ) (n : ℕ) : (s_seq s n).re = (1/2) * (2 * s.re) ^ (2^n) := by
  induction' n with n ih;
  · norm_num [ s_seq ] ; ring;
  · rw [ pow_succ, pow_mul' ] ; rw [ s_seq_re ] ; rw [ ih ] ; ring;
    norm_num [ pow_mul' ]

/-
Helper lemmas for r^(2^n) convergence. Theorem: Re(s_n) converges to 0 or infinity based on Re(s).
-/
theorem tendsto_pow_two_pow_atTop_zero {r : ℝ} (h0 : 0 ≤ r) (h1 : r < 1) : Filter.Tendsto (fun n : ℕ => r ^ (2 ^ n)) Filter.atTop (nhds 0) := by
  exact tendsto_pow_atTop_nhds_zero_of_lt_one h0 h1 |> Filter.Tendsto.comp <| Nat.tendsto_pow_atTop_atTop_of_one_lt one_lt_two

theorem tendsto_pow_two_pow_atTop_atTop {r : ℝ} (h1 : 1 < r) : Filter.Tendsto (fun n : ℕ => r ^ (2 ^ n)) Filter.atTop Filter.atTop := by
  exact tendsto_pow_atTop_atTop_of_one_lt h1 |> Filter.Tendsto.comp <| Nat.tendsto_pow_atTop_atTop_of_one_lt one_lt_two

theorem sigma_seq_convergence (s : ℂ) (h_pos : 0 < s.re) (h_ne : s.re ≠ 1/2) :
  (s.re < 1/2 → Filter.Tendsto (fun n => (s_seq s n).re) Filter.atTop (nhds 0)) ∧
  (s.re > 1/2 → Filter.Tendsto (fun n => (s_seq s n).re) Filter.atTop Filter.atTop) := by
    have h_exp_zero : ∀ n, (s_seq s n).re = (1/2) * (2 * s.re) ^ (2 ^ n) := by
      exact fun n ↦ s_seq_re_closed_form s n;
    constructor <;> intro h <;> simp_all +decide [ pow_mul ];
    · exact le_trans ( tendsto_const_nhds.mul ( tendsto_pow_atTop_nhds_zero_of_lt_one ( by positivity ) ( by linarith ) |> Filter.Tendsto.comp <| Nat.tendsto_pow_atTop_atTop_of_one_lt one_lt_two ) ) ( by norm_num );
    · exact Filter.Tendsto.const_mul_atTop ( by norm_num ) ( tendsto_pow_atTop_atTop_of_one_lt ( by linarith ) |> Filter.Tendsto.comp <| Nat.tendsto_pow_atTop_atTop_of_one_lt one_lt_two )

/-
Lemma: If 0 < Re(s) < 1/2, then s_seq s n converges to 0.
-/
theorem s_seq_tendsto_zero (s : ℂ) (h_pos : 0 < s.re) (h_lt : s.re < 1/2) :
  Filter.Tendsto (fun n => s_seq s n) Filter.atTop (nhds 0) := by
  -- We show that |s_n| converges to 0.
  apply tendsto_zero_iff_norm_tendsto_zero.mpr
  -- |s_{n+1}| = 2 * Re(s_n) * |s_n|
  -- Since Re(s_n) -> 0, eventually 2 * Re(s_n) < 1/2.
  -- This implies |s_n| decays geometrically.
  -- Since the imaginary part is bounded and tends to 0, the norm of s_seq s n will also tend to 0.
  have h_im_zero : Filter.Tendsto (fun n => (s_seq s n).im) Filter.atTop (nhds 0) := by
    -- By definition of $s_seq$, we know that $(s_seq s n).im = 2 * (s_seq s (n - 1)).re * (s_seq s (n - 1)).im$ for $n \geq 1$.
    have h_im_recurrence : ∀ n ≥ 1, (s_seq s n).im = 2 * (s_seq s (n - 1)).re * (s_seq s (n - 1)).im := by
      rintro ( _ | n ) <;> simp +decide [ *, Complex.ext_iff ];
      rw [ show s_seq s ( n + 1 ) = 2 * ( s_seq s n |> Complex.re ) * ( s_seq s n ) from rfl ] ; norm_num [ Complex.ext_iff ];
    -- By induction, we can show that $(s_seq s n).im = (2 * s.re) ^ (2 ^ n - 1) * s.im$ for all $n \geq 1$.
    have h_im_formula : ∀ n ≥ 1, (s_seq s n).im = (2 * s.re) ^ (2 ^ n - 1) * s.im := by
      intro n hn
      induction' n, hn using Nat.le_induction with n hn ih;
      · norm_num [ h_im_recurrence ];
        rfl;
      · erw [ h_im_recurrence _ ( Nat.le_succ_of_le hn ), ih, s_seq_re_closed_form ] ; ring;
        rw [ show 2 ^ n * 2 - 1 = ( 2 ^ n - 1 ) + 2 ^ n by zify ; norm_num ; ring ] ; norm_num [ pow_add, pow_mul ] ; ring;
    rw [ Filter.tendsto_congr' ( Filter.eventuallyEq_of_mem ( Filter.Ici_mem_atTop 1 ) h_im_formula ) ] ; simpa using Filter.Tendsto.mul ( tendsto_pow_atTop_nhds_zero_of_lt_one ( by positivity ) ( show 2 * s.re < 1 by linarith ) |> Filter.Tendsto.comp <| Filter.tendsto_sub_atTop_nat 1 |> Filter.Tendsto.comp <| Nat.tendsto_pow_atTop_atTop_of_one_lt one_lt_two ) tendsto_const_nhds;
  -- Since the real part also tends to 0, the norm of s_seq s n will also tend to 0.
  have h_re_zero : Filter.Tendsto (fun n => (s_seq s n).re) Filter.atTop (nhds 0) := by
    convert sigma_seq_convergence s h_pos ( by linarith ) |>.1 h_lt using 1;
  convert Filter.Tendsto.sqrt ( Filter.Tendsto.add ( h_re_zero.pow 2 ) ( h_im_zero.pow 2 ) ) using 2 <;> norm_num [ Complex.normSq, Complex.norm_def ] ; ring

/-
Theorem: The scaling sequence of zeros leads to a contradiction if Re(s) != 1/2.
-/
theorem scaling_sequence_contradiction (s : ℂ) (h_zero_seq : ∀ n, riemannZeta (s_seq s n) = 0) (h_pos : 0 < s.re) (h_ne : s.re ≠ 1/2) : False := by
  have h_conv := sigma_seq_convergence s h_pos h_ne
  by_cases h_lt : s.re < 1/2
  · -- Case < 1/2: s_n -> 0
    have h_lim : Filter.Tendsto (fun n => s_seq s n) Filter.atTop (nhds 0) :=
      s_seq_tendsto_zero s h_pos h_lt
    exact zero_limit_contradiction (fun n => s_seq s n) h_lim h_zero_seq
  · -- Case > 1/2: Re(s_n) -> infinity
    have h_gt : s.re > 1/2 := lt_of_le_of_ne (not_lt.mp h_lt) h_ne.symm
    have h_lim_inf : Filter.Tendsto (fun n => (s_seq s n).re) Filter.atTop Filter.atTop := h_conv.2 h_gt
    -- Eventually Re(s_n) > 1
    have h_eventually : ∀ᶠ n in Filter.atTop, 1 < (s_seq s n).re := h_lim_inf (Filter.Ioi_mem_atTop 1)
    obtain ⟨n, hn⟩ := h_eventually.exists
    -- But zeta(s_n) = 0 implies Re(s_n) <= 1 (since no zeros for Re(s) > 1)
    have h_nz : riemannZeta (s_seq s n) ≠ 0 := riemannZeta_ne_zero_of_one_lt_re hn
    exact h_nz (h_zero_seq n)

/-
Theorem: RH is equivalent to FaithfulReconstruction for zeros in the strip. Proof uses the fact that non-trivial zeros are in the strip.
-/
theorem rh_equivalent_to_faithful_reconstruction :
  (∀ s, riemannZeta s = 0 → 0 < s.re ∧ s.re < 1 → FaithfulReconstruction s.re) ↔ RiemannHypothesis := by
  rw [RiemannHypothesis]
  constructor
  · intro h s h_zero h_not_trivial h_ne_one
    -- We need to show s.re = 1/2.
    -- We assume the standard fact that non-trivial zeros lie in the critical strip.
    have h_strip : 0 < s.re ∧ s.re < 1 := by
      -- This requires standard results about the zero-free regions and trivial zeros.
      -- Trivial zeros are at -2, -4, ...
      -- No zeros for Re(s) >= 1 (except pole at 1, but s != 1).
      -- No zeros for Re(s) <= 0 except trivial ones.
      constructor <;> contrapose! h_not_trivial;
      · have := @riemannZeta_ne_zero_of_one_le_re ( 1 - s ) ?_ <;> simp_all +decide [ sub_eq_iff_eq_add ];
        have := @riemannZeta_one_sub s; simp_all +decide [ sub_eq_iff_eq_add ] ;
        rcases this with ⟨ n, rfl ⟩ ; norm_num at *;
        have := @riemannZeta_neg_nat_eq_bernoulli n; simp_all +decide [ Nat.cast_add_one_ne_zero ] ;
        rcases Nat.even_or_odd' n with ⟨ k, rfl | rfl ⟩ <;> norm_num [ bernoulli_eq_bernoulli'_of_ne_one, Nat.succ_eq_add_one ] at *;
        · exact ⟨ k - 1, by cases k <;> aesop ⟩;
        · have := @hasSum_zeta_nat ( k + 1 ) ; simp_all +decide [ Nat.succ_eq_add_one, mul_add ] ;
          have := this.tsum_eq; simp_all +decide [ Nat.factorial_ne_zero, bernoulli ] ;
          exact absurd this <| ne_of_gt <| lt_of_lt_of_le ( by positivity ) <| Summable.le_tsum ( by exact Real.summable_nat_pow_inv.2 <| by linarith ) 1 <| by intros; positivity;
      · exact absurd h_zero <| by { exact riemannZeta_ne_zero_of_one_le_re h_not_trivial }
    have h_faithful := h s h_zero h_strip
    rw [faithfulReconstruction_iff_half] at h_faithful
    exact h_faithful
  · intro h s h_zero h_strip
    rw [faithfulReconstruction_iff_half]
    apply h s h_zero
    · -- Show s is not a trivial zero
      intro ⟨n, hn⟩
      have h_re : s.re = -2 * (n + 1) := by
        rw [hn]
        simp
      have h_neg : s.re < 0 := by
        rw [h_re]
        linarith
      linarith [h_strip.1]
    · -- Show s != 1
      intro h_eq
      rw [h_eq] at h_strip
      norm_num at h_strip

/-
Lemma: Non-trivial zeros of the Riemann Zeta function lie in the critical strip (0 < Re(s) < 1).
-/
theorem non_trivial_zeros_in_strip (s : ℂ) (h_zero : riemannZeta s = 0) (h_not_trivial : ¬∃ (n : ℕ), s = -2 * (↑n + 1)) (h_ne_one : s ≠ 1) :
  0 < s.re ∧ s.re < 1 := by
    by_cases h_real_part : s.re ≤ 0;
    · have := @riemannZeta_ne_zero_of_one_le_re ( 1 - s ) ?_ <;> simp_all +decide [ Complex.ext_iff ];
      rw [ show riemannZeta ( 1 - s ) = riemannZeta s * ( 2 ^ s * Real.pi ^ ( s - 1 ) * Complex.sin ( Real.pi * s / 2 ) * Complex.Gamma ( 1 - s ) ) from ?_ ] at this;
      · simp_all +decide [ Complex.ext_iff ];
      · rw [ riemannZeta_one_sub ];
        · rw [ show riemannZeta s = 0 from by simpa [ Complex.ext_iff ] using h_zero ] ; ring;
        · intro n hn; simp_all +decide [ Complex.ext_iff ] ;
          rcases Nat.even_or_odd' n with ⟨ k, rfl | rfl ⟩ <;> norm_num at *;
          · rcases k with ( _ | k ) <;> norm_num at *;
            norm_num [ show riemannZeta 0 = -1 / 2 by exact riemannZeta_zero ] at *;
          · have := @riemannZeta_neg_nat_eq_bernoulli ( 2 * k + 1 ) ; simp_all +decide [ Nat.mul_succ, Nat.add_mul_div_left ] ;
            norm_cast at * ; simp_all +decide [ Nat.even_add_one ];
            norm_cast at * ; simp_all +decide [ Nat.even_add_one ];
            have := @hasSum_zeta_nat ( k + 1 ) ; simp_all +decide [ Nat.mul_succ, Nat.add_mul_div_left ] ;
            exact absurd ( this.tsum_eq ) ( by exact ne_of_gt <| lt_of_lt_of_le ( by positivity ) <| Summable.le_tsum ( by exact Real.summable_nat_pow_inv.2 <| by linarith ) 1 <| by intros; positivity );
        · aesop;
    · by_cases h_real_part : s.re ≥ 1;
      · exact absurd h_zero <| by exact riemannZeta_ne_zero_of_one_le_re h_real_part;
      · constructor <;> linarith


/-
Theorem: RH is equivalent to FaithfulReconstruction for zeros in the strip. Proof uses the fact that non-trivial zeros are in the strip.
-/
theorem rh_iff_faithful :
  (∀ s, riemannZeta s = 0 → 0 < s.re ∧ s.re < 1 → FaithfulReconstruction s.re) ↔ RiemannHypothesis := by
  rw [RiemannHypothesis]
  constructor
  · intro h s h_zero h_not_trivial h_ne_one
    have h_strip : 0 < s.re ∧ s.re < 1 := non_trivial_zeros_in_strip s h_zero h_not_trivial h_ne_one
    have h_faithful := h s h_zero h_strip
    rw [faithfulReconstruction_iff_half] at h_faithful
    exact h_faithful
  · intro h s h_zero h_strip
    rw [faithfulReconstruction_iff_half]
    apply h s h_zero
    · intro ⟨n, hn⟩
      have h_re : s.re = -2 * (n + 1) := by
        rw [hn]
        simp
      have h_neg : s.re < 0 := by
        rw [h_re]
        linarith
      linarith [h_strip.1]
    · intro h_eq
      have h_re_one : s.re = 1 := by rw [h_eq]; simp
      linarith [h_strip.2, h_re_one]

/-
Definition of BridgeProperty. Theorem: BridgeProperty implies RH. Proof uses scaling sequence.
-/
def BridgeProperty : Prop := ∀ s : ℂ, riemannZeta s = 0 → 0 < s.re ∧ s.re < 1 → riemannZeta (2 * s.re * s) = 0


theorem bridge_implies_rh (h_bridge : BridgeProperty) : RiemannHypothesis := by
  rw [RiemannHypothesis]
  intro s h_zero h_not_trivial h_ne_one
  have h_strip : 0 < s.re ∧ s.re < 1 :=
    non_trivial_zeros_in_strip s h_zero h_not_trivial h_ne_one
  by_contra h_ne_half

  let P : ℕ → Prop := fun n =>
    riemannZeta (s_seq s n) = 0 ∧
    0 < (s_seq s n).re ∧
    (s_seq s n).re < 1

  have hP : ∀ n, P n := by
    intro n
    induction' n with n ihn
    · exact ⟨h_zero, h_strip.1, h_strip.2⟩
    · rcases ihn with ⟨hz, hpos, hlt⟩

      have hz' : riemannZeta (s_seq s (n + 1)) = 0 := by
        rw [s_seq]
        exact h_bridge (s_seq s n) hz ⟨hpos, hlt⟩

      have h_not_trivial' : ¬ ∃ k : ℕ, s_seq s (n + 1) = -2 * ((k : ℂ) + 1) := by
        intro htriv
        rcases htriv with ⟨k, hk⟩
        have h_re : (s_seq s (n + 1)).re = -2 * (k + 1) := by
          rw [hk]
          simp
        -- It is enough to know Re(s_{n+1}) > 0.
        have h_pos' : 0 < (s_seq s (n + 1)).re := by
          -- This should follow from the definition of s_seq and hpos.
          -- If needed, replace with a dedicated lemma about the real-part recurrence.
          rw [s_seq]
          simp [Complex.mul_re, hpos.le]
          nlinarith
        linarith

      have h_ne_one' : s_seq s (n + 1) ≠ 1 := by
        intro h1
        have : riemannZeta (1 : ℂ) = 0 := by
          simpa [h1] using hz'
        exact riemannZeta_one_ne_zero this

      have h_strip' : 0 < (s_seq s (n + 1)).re ∧ (s_seq s (n + 1)).re < 1 :=
        non_trivial_zeros_in_strip (s_seq s (n + 1)) hz' h_not_trivial' h_ne_one'

      exact ⟨hz', h_strip'.1, h_strip'.2⟩

  have h_seq_zero : ∀ n, riemannZeta (s_seq s n) = 0 := by
    intro n
    exact (hP n).1

  exact scaling_sequence_contradiction s h_seq_zero h_strip.1 h_ne_half


theorem rh_implies_bridge (h : RiemannHypothesis) : BridgeProperty := by
  intro s hs hstrip
  have h_not_trivial : ¬ ∃ n : ℕ, s = -2 * ((n : ℂ) + 1) := by
    intro htriv
    rcases htriv with ⟨n, hn⟩
    have : s.re = -2 * (n + 1) := by
      rw [hn]
      simp
    linarith [hstrip.1]
  have h_ne_one : s ≠ 1 := by
    intro h1
    have : s.re = 1 := by rw [h1]; simp
    linarith [hstrip.2]
  have hre : s.re = 1 / 2 := h s hs h_not_trivial h_ne_one
  simpa [hre] using hs




/-
Theorem: BridgeProperty is equivalent to RH.
-/
theorem bridge_iff_rh : BridgeProperty ↔ RiemannHypothesis := by
  constructor
  · intro h
    exact bridge_implies_rh h
  · intro h
    exact rh_implies_bridge h

#check RiemannHypothesis
#check FaithfulReconstruction
#check scaling_sequence_contradiction
#check riemannZeta_ne_zero_of_one_le_re
#check riemannZeta_one_sub
#check riemannZeta_zero
#check hasSum_zeta_nat
#check non_trivial_zeros_in_strip
#check rh_equivalent_to_faithful_reconstruction
#check bridge_implies_rh
#check bridge_iff_rh
#print axioms bridge_iff_rh
#print axioms bridge_implies_rh
#print BridgeProperty
#print RiemannHypothesis
